### ISSUE TITLE
Espn needs a bug fix

### ISSUE THREAD

**Issue by disableddabel** [dtankdempse/thetvapp-m3u#11]
Espn 1 and 2 is not working

**Comment by ttx99** [comment]
science channel is just blank for me espn, is fine
![1](https://github.com/user-attachments/assets/86d2b7f4-0840-42c2-93d9-e04d4c856a7b)

**Comment by dtankdempse** [comment]
@ttx99 Science has been fixed. Refresh your playlist.

**Comment by stein-dev** [comment]
@ttx99 Can you please tell me what app are you using?

**Comment by disableddabel** [comment]
IPTV SMARTERS PRO

**Comment by jblaze3** [comment]
I am having similar problem where playlist is recently refreshed but ESPN 1 and 2 only plays for about ten minutes then gets 403 error, but while other channels plays fine. I am using tivimate.

**Comment by ttx99** [comment]
@stein-dev if your using Windows OS there no point telling you cause it only works in linux OS

**Comment by ttx99** [comment]
@dtankdempse  fixed thx
![1](https://github.com/user-attachments/assets/d8febb79-e9f6-46d8-bd1b-a4e00eeb2d61)

**Comment by ttx99** [comment]
@stein-dev 
https://github.com/linuxmint/hypnotix

**Comment by disableddabel** [comment]
Is there a App for my Samsung Odyssey
