### ISSUE TITLE
For some reason I can not see sports programs on M3U IPTV app

### ISSUE THREAD

**Issue by disableddabel** [dtankdempse/thetvapp-m3u#15]
![IMG_4113](https://github.com/user-attachments/assets/1952b162-b2df-4712-9cfe-afa67bb8c047)

**Comment by codinandhaulin** [comment]
There was an update to the readme today that addresses this:

`Note: Due to recent changes on TheTVApp's website, events are currently not being added to the playlist. We are actively looking into the issue.`

**Comment by codinandhaulin** [comment]
@dtankdempse Good luck, brother.  This would be epic!
