### ISSUE TITLE
Could you please make a hotfix it's not working on NJAAY IPTV

### ISSUE THREAD

**Issue by disableddabel** [dtankdempse/thetvapp-m3u#17]
Can you please fix it before the blazers game tonight

**Comment by disableddabel** [comment]
Please please

**Comment by dtankdempse** [comment]
I've been working on it since yesterday. It's wasn't just a quick and easy fix. Try being a little more patient, Or, consider subscribing to a service provider if you need something more reliable.

It's fixed now. Refresh your playlist.
