### ISSUE TITLE
An error occured: code 403 trying 1/5

### ISSUE THREAD

**Issue by Kevsosmooth** [dtankdempse/thetvapp-m3u#20]
Upon watching BET channel and not testing yet with any other channels every few minutes or really a random time frame but closely together I keep getting the error stated in the issue subject line. 

Am I getting this error because it's following mytvapp links because for the most part my internet is pretty good. 

Is this a known problem?

**Comment by dtankdempse** [comment]
I’ve also noticed this happening, particularly during peak hours. Their servers might just be handling a large amount of traffic, but it should settle down and return to normal at some point.
