### ISSUE TITLE
Is it possible to make a m3u playlist from USA tv?

### ISSUE THREAD

**Issue by Kevsosmooth** [dtankdempse/thetvapp-m3u#21]
So aside from this I know of a stremio account that you can add USA TV addon and get many similar channels to this but some being different would it even be possible to follow the urls the same way you follow these?
I know the owner that made usa tv also follows many website to ensure the stream is always running and channels are active. The channels work well but with yours obviously you get a epg and can add it to a iptv app where the other one its only on stremio

**Comment by Kevsosmooth** [comment]
Ok so upon looking its relatively easy as they give you the m3u link but im not sure if it changes like the on THETVAPP

#EXTINF:-1,TELEMUNDO
http://streamsy.online:2999/live/juanv/04bodwaga0/281.m3u8

#EXTINF:-1,UNIVISON
http://streamsy.online:2999/live/juanv/04bodwaga0/1522.m3u8

These are two I was able to stream on my local computer with vlc. What I noticed is the 281 and 1522 and was wondering if they had a order of 1 to however many they have

**Comment by dtankdempse** [comment]
"I'll look into it. If you have a link to the actual addon, please post it.

Regarding the two links you mentioned, there’s more happening than you might realize. These links appear to be from an Xtream Codes server:

    http://streamsy.online:2999/player_api.php?username=juanv&password=04bodwaga0
    http://streamsy.online:2999/get.php?username=juanv&password=04bodwaga0&type=m3u_plus

It looks like they could be using several of these types of servers, but I can't be sure until I investigate further."

**Comment by Kevsosmooth** [comment]
Interesting how did you get the links to appear as so with the username and password url. 

Also here are the steps

If using a pc

Web.stremio.com

No need to make an account unless you plan using it

Add the addon with this link

https://stremio-addons.netlify.app/usa-tv

Instead of clicking install i usally just click copy link then headover to addon section of stremio and add it

Lastly once installed go to Discover on stremio

Sort by tv channels and all them will pop up.

**Comment by Kevsosmooth** [comment]
But I did copy the the playlist you sent and they are like 1777 channels but one of the main list are called USA

**Comment by dtankdempse** [comment]
The URL pattern in the links you shared follows the typical structure used by servers running Xtream Codes software, as they all follow the same format.

`http://HOST:PORT/player_api.php?username=USER&password=PASS`
`http://HOST:PORT/get.php?username=USER&password=PASS&type=m3u_plus`

The following URL lists all USA TV channels:

`https://848b3516657c-usatv.baby-beamup.club/catalog/tv/all.json`

I’ve created a converter that transforms their JSON into an M3U playlist, which you can find here:

https://github.com/dtankdempse/stremio-usa-tv-m3u/tree/main

Most of the channels also include EPG guide data.

**Comment by Kevsosmooth** [comment]
Your definitely a beast bro. Thank you.

**Comment by Kevsosmooth** [comment]
This one you do not have to refresh you think right?

**Comment by dtankdempse** [comment]
Most apps refresh once a day, so it's best to keep it at the default setting. If more channels are added, they'll automatically be included in the playlist during the next refresh.

**Comment by Kevsosmooth** [comment]
That makes sense also would it be relatively easy to grab the Dominican channels as well? I was setting this up a spanish member and these are probably the best channels they would want

Thank you again

**Comment by Kevsosmooth** [comment]
Well I know you have guides for a lot of things this is nothing something you made a guy how to do right?

**Comment by dtankdempse** [comment]
> hat makes sense also would it be relatively easy to grab the Dominican channels as well? I was setting this up a spanish member and these are probably the best channels they would want

If the channels are coming from another Stremio add-on, they're easy to add since they all follow Stremio's required format. If you have any additional sources for channels, feel free to share them, and I'll take a look.

> now you have guides for a lot of things this is nothing something you made a guy how to do right?

Honestly, with AI, coding has become much faster. I probably write about 10-15% of my scripts now, while ChatGPT handles the other 90%. Once you understand the logic of what the script needs to do, you just outline it, and it generates the code for you.

**Comment by Kevsosmooth** [comment]
I do the same thing when using chatgpt but you still would have to understand what your evening looking for lol. For example you found the password part earlier and I wasn't sure to even know how to look for that.

Well i mean I was just going to make a single playlist with the rest of the spanish items on from that main one you sent me earlier 

http://streamsy.online:2999/get.php?username=juanv&password=04bodwaga0&type=m3u_plus

They have one called

Latinamerica, republica dominican, telemundo network and univison/unimas network

But it seems you set up a cloudflare that keep track off these network incase they make a change where as I know how to create just the m3u file locally but im not sure if it would change with any update they make

**Comment by dtankdempse** [comment]
Use something like M3U4U. Much better for what you are looking to do. Follow this guide.

Signup for https://m3u4u.com and login.

Go here https://m3u4u.com/playlists Click on the 'Create playlist' button, then give your playlist a name and select 'M3U Url'. Click Save, then Add the url to the playlist.

After you added the url go here https://m3u4u.com/epgs and click the pencil next to your list. Select m3u4u as the 'Source of EPG' and click save.

Next go to https://m3u4u.com/playlisteditor and select your playlist. Here you can use the tools to remove the counties and groups you dont want in your playlist.

Go to this page https://m3u4u.com/epgeditor to start assigning the channels to the epg. There is also an auto assign tool you can use.

Once you are all done and satisficed with your list, go here https://m3u4u.com/playlists and click the down arrow button.

Their discord: https://discord.gg/kveNCSEW

**Comment by Kevsosmooth** [comment]
I see, yes I do have a m3u4u account but ok so I would most likely add that big huge main list that had like 1700 channels and then narrow what I want down from there correcT?

**Comment by dtankdempse** [comment]
Right, you can narrow it down using this:

"Next go to https://m3u4u.com/playlisteditor and select your playlist. Here you can use the tools to remove the counties and groups you dont want in your playlist."

**Comment by Kevsosmooth** [comment]
Ok ill try following those steps... do you know if that works with yours as well to merge them this way I can have a nice selection of channels because m3u4 only lets you update every 24 hours and tvapp must be updated every 8 hrs or so

**Comment by dtankdempse** [comment]
Yeah, TheTVApp might not work as smoothly with the merging. All the other playlists will work fine, but TheTVApp will need more frequent updates. You're right about that.

**Comment by Kevsosmooth** [comment]
Sounds good heard all I needed to hear appreciate the help

**Comment by ttx99** [comment]
@dtankdempse can you give me the playlist bro pls ttx99@protonmail.com

**Comment by dtankdempse** [comment]
> @dtankdempse can you give me the playlist bro pls [ttx99@protonmail.com](mailto:ttx99@protonmail.com)

I removed the repo after talking with the developer of the plugin. 

You can still find the playlist here: http://m3u4u.com/m3u/5z3endxdwzudwpqrnqpk

**Comment by Kevsosmooth** [comment]
@dtankdempse may I know exactly what you moved? Is this the channel from usatv because im watching it and seems to work with the link from before

**Comment by dtankdempse** [comment]
> @dtankdempse may I know exactly what you moved? Is this the channel from usatv because im watching it and seems to work with the link from before

Send me a dm on discord: dtanks_86578

**Comment by Kevsosmooth** [comment]
http://streamsy.online:2999/get.php?username=venomj&password=EmoOmOskzq&type=m3u_plus


Do you know how I would be able to add this to vlc or another app directly do you think i have to add headers ?

**Comment by dtankdempse** [comment]
No, this doesn't require any headers. You can add it as an M3U playlist in any app, and the streams should play without issues. Alternatively, you can use it as an Xtream Codes server. For VLC, go to Media > Open Network Stream and paste the URL into the textbox..

**Comment by Kevsosmooth** [comment]
I had to use this format nothing else worked

:
http://streamsy.online:2999/get.php?username=venomj&password=EmoOmOskzq&type=m3u_plus&output=m3u8





Thank you,

*Kevin S. *
