### ISSUE TITLE
I don't see nfl

### ISSUE THREAD

**Issue by disableddabel** [dtankdempse/thetvapp-m3u#22]
P

**Comment by dtankdempse** [comment]
All of the channels and events that TheTVApp has listed on their website for the day is included in the playlist.

**Comment by disableddabel** [comment]
No some days it doesn't like today

**Comment by dtankdempse** [comment]
Then maybe you are be rate limited and the current playlist is not being downloaded.

![image](https://github.com/user-attachments/assets/a9bd1187-8733-405b-ac6f-7a2be78cc005)

Open this in a browser: https://bit.ly/tta-m3u

Then in a notepad search for: group-title="NFL Football"

They are in the playlist. If you dont see them when you load the playlist within your app it's something on your end.

**Comment by disableddabel** [comment]
Thanks, I'll check it out.
