### ISSUE TITLE
The groups looks very un-useful

### ISSUE THREAD

**Issue by disableddabel** [dtankdempse/thetvapp-m3u#26]
The old groups looks better and cleaner

**Comment by dtankdempse** [comment]
The groups are staying. However, ill add a url parameter that you can include to use the old way.

**Comment by dtankdempse** [comment]
Ok, here use this for the old single grouping:

``http://tinyurl.com/tta-m3u?v=old``

**Comment by disableddabel** [comment]
Ok well it include sports and ppv

**Comment by dtankdempse** [comment]
Yes, it's exactly the way it was before.

**Comment by disableddabel** [comment]
Th
