### ISSUE TITLE
Buffering

### ISSUE THREAD

**Issue by E3RTT** [dtankdempse/thetvapp-m3u#27]
It keeps buffering on tivimate

**Comment by E3RTT** [comment]
It's been buffering all night and I'm using tivimate on very large buffer

**Comment by dtankdempse** [comment]
I'm considering creating and releasing a Dockerfile for this site. It's using too many resources for me to want to continue supporting and running the scripts directly. I'm sorry, but with so many users now requesting playlists, there's not much more I can do.

**Comment by E3RTT** [comment]
Alright, I'm not intending to annoy or pester you, I just don't know if you're aware when it does, hell for one guy running it you do a damn good job.

**Comment by E3RTT** [comment]
It's buffering every few seconds

**Comment by E3RTT** [comment]
Oh I'm so so sorry I just realized its not the m3u, the website is buffering like crazy.

**Comment by dtankdempse** [comment]
I'm not experiencing any buffering issues. Have you tried lowering the video quality by clicking the gear icon on the web player to see if that helps?

**Comment by E3RTT** [comment]
It was this morning thetvapp website was buffering like crazy, within 20 minutes it quit.

**Comment by E3RTT** [comment]
It's buffering like crazy

**Comment by Toylerrr** [comment]
> I'm considering creating and releasing a Dockerfile for this site. It's using too many resources for me to want to continue supporting and running the scripts directly. I'm sorry, but with so many users now requesting playlists, there's not much more I can do.

I would appreciate this btw
