### ISSUE TITLE
Channels not working as of 10/3?

### ISSUE THREAD

**Issue by G0C0UGS** [dtankdempse/thetvapp-m3u#3]
Service has been great, thank you! As of today, I can't watch any channels. EPG is still live and accurate but channel can't be accessed. Help would be appreciated!

**Comment by dtankdempse** [comment]
"Since the playlist is dynamically generated, we recommend setting your application to reimport the playlist every 8 hours to ensure it remains up-to-date. If you encounter a 403 error, it indicates that your playlist has expired and needs to be refreshed."

Try refreshing your playlist.

**Comment by G0C0UGS** [comment]
This worked. Can't believe I didn't do this before reaching out. Thank you again!

**Comment by dtankdempse** [comment]
No problem.
