### ISSUE TITLE
No channels are showing 

### ISSUE THREAD

**Issue by disableddabel** [dtankdempse/thetvapp-m3u#31]
Please fix

**Comment by dtankdempse** [comment]
There is no issue with the playlist. However, you may have hit the rate limit by making too many requests. The limit is 5 playlist requests within a 2 hour period. Once you exceed that limit, you will be blocked, and a dummy playlist will begin loading instead. Check your applications to ensure they aren't trying to update the playlist to often.

**Comment by Aetherinox** [comment]
I can confirm I just loaded this playlist up, and the very first video I clicked loaded within 5-10 seconds.

Using Jellyfin. Didn't need threadfin or anything else.

**Comment by disableddabel** [comment]
Can you please make a version that will work with smarters pro

**Comment by dtankdempse** [comment]
Change it to what? This playlist follows the standard M3U format. If Smarters Pro is having trouble importing it, the issue likely lies with their software. Perhaps you could ask them to point out any specific formatting errors they believe are present in the playlist?

I double-checked the formatting with ChatGPT:
https://chatgpt.com/share/674b9079-7dd0-800a-aba4-8f93bedaccb3

I ran some test with Smarters and managed to load the playlist. However, the channels didn't play. If you look at the image below, you'll notice that the URL is being appended to the channel name, which seems to be causing the issue.

![smarters-issue-1](https://github.com/user-attachments/assets/b78a797d-2686-4852-b8e7-fcc88292d574)

The problem for some reason is the logo.
```
#EXTINF:-1 tvg-id="A.and.E.US.-.Eastern.Feed.us" tvg-name="A&E" tvg-logo="http://schedulesdirect-api20141201-logos.s3.dualstack.us-east-1.amazonaws.com/stationLogos/s51529_dark_360w_270h.png" group-title="Entertainment",A&E 
https://v3.thetvapp.to/hls/AEEast/index.m3u8?token=VFRxNEFMd0lBYkc2WUE2bTdpZXJsaTF4WFVSU2xmYUFBdTJlS0FOQw==
```

Now in this picture below I removed the logo and the channel actually played:

![smarters-test](https://github.com/user-attachments/assets/d7ff0a4f-bc3b-4316-9862-61d26f9a59e6)
```
#EXTINF:-1 tvg-id="A.and.E.US.-.Eastern.Feed.us" tvg-name="A&E" tvg-logo="" group-title="Entertainment",A&E 
https://v3.thetvapp.to/hls/AEEast/index.m3u8?token=VFRxNEFMd0lBYkc2WUE2bTdpZXJsaTF4WFVSU2xmYUFBdTJlS0FOQw==
```

The issue appears to be on Smarters' end, as this is a standard M3U playlist that their software should handle without any trouble. If there's a problem with their software, they’ll need to address it. However, if they can identify any specific issues with the formatting, I’ll be happy to review and fix it if necessary.

**Comment by disableddabel** [comment]
Thanks, I'll look into it.
