### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by E3RTT** [dtankdempse/thetvapp-m3u#32]
It's not showing what's on, except for a few channels

**Comment by E3RTT** [comment]
Still no luck, I'm using implayer and haven't ever had issues where the epg wasn't working.

**Comment by dtankdempse** [comment]
Yeah, you're right. My EPG data that I was seeing was using an earlier download. I'm checking on the problem now,

**Comment by E3RTT** [comment]
Oh, okay thank you!

**Comment by dtankdempse** [comment]
![Capture](https://github.com/user-attachments/assets/6b596301-c617-416d-a92e-09df14560291)

Looks like I have to remap the channels again. I'll start now, but it make take a couple of days.

**Comment by E3RTT** [comment]
Oh, alright that's fine man, thanks for responding so quickly.
