### ISSUE TITLE
It saying rate limit reached on your playlist 

### ISSUE THREAD

**Issue by disableddabel** [dtankdempse/thetvapp-m3u#37]
![IMG_4194](https://github.com/user-attachments/assets/0d418cce-d7d0-43c6-b233-94e3b4e8f144)

**Comment by dtankdempse** [comment]
The server is requesting the playlist too frequently and has been blocked. You won't be able to add the playlist to m3u4u because the web server has already made more than five requests in the past two hours.

**Comment by disableddabel** [comment]
Ok will i be able to later
