### ISSUE TITLE
Is CLI possible for TVAPP playlist 

### ISSUE THREAD

**Issue by ttx99** [dtankdempse/thetvapp-m3u#47]
for context: https://github.com/pystardust/ani-cli

**Comment by dtankdempse** [comment]
I'm not sure I fully understand what you're trying to achieve by using the command line. Could you explain that in more detail?

**Comment by ttx99** [comment]
like when you type for example tvapp at terminal and it presents all the channel and when you select one vlc or mpv player plays the m3u link
Like this

Uploading 2024-12-19 20-12-46.mp4…

**Comment by dtankdempse** [comment]
You’ll need a completely different script to achieve what you’re looking for. I explained the process to AI, and it generated a pretty decent script. If you want the script to do something different, just load it into ChatGPT and describe the changes you need. This script is written in Python, and the only dependency required is the requests library.

[m3u-tool.zip](https://github.com/user-attachments/files/18200196/m3u-tool.zip)

**Comment by ttx99** [comment]
thx
