### ISSUE TITLE
EPG BUG??

### ISSUE THREAD

**Issue by PD-TheKrazy0ne** [dtankdempse/thetvapp-m3u#53]
I am experiencing an issue with the epg and the Event Listings.... NFL for instance.... right now the link for the Bills vs Jets game is https://thetvapp.to/event/new-york-jets-vs-buffalo-bills-eb5a71180b3558fdc20a896e98c00385/ 

I assume "eb5a71180b3558fdc20a896e98c00385" should be the channel-id in the epg but when i look in the m3u i have generated on my server it shows as:

#EXTINF:-1 tvg-id="9f6196e5faf6cb3b93c4237581f1bbff" tvg-name="New York Jets vs. Buffalo Bills" tvg-logo="https://www.thesportsdb.com/images/media/league/badge/hstx2k1719402847.png/preview" group-title="NFL Football",1:01 PM - New York Jets vs. Buffalo Bills - 01:01 PM EST - (12/29/2024)
https://v12.thetvapp.to/hls/WCBSDT1/index.m3u8?token=SkRzTkFUSkxaaTkzNTVkQlNKazJlTmN5cWlKMzBpOTJWNFRGQ1UwVg==

"eb5a71180b3558fdc20a896e98c00385" is not found anywhere in the m3u or your epg...

your epg lists the game as this:

  channel id="9f6196e5faf6cb3b93c4237581f1bbff"
    display-name>New York Jets vs. Buffalo Bills - 01:01 PM EST - (12/29/2024)
"https://www.thesportsdb.com/images/media/league/badge/hstx2k1719402847.png/preview"
channel

is there something I have set wrong?

**Comment by dtankdempse** [comment]
The `eb5a71180b3558fdc20a896e98c00385` hash is unrelated to the EPG; it’s a hash generated by TheTVApp for their internal linking structure. On the other hand, the `9f6196e5faf6cb3b93c4237581f1bbff` hash is assigned to channels in both the EPG and M3U. If guide information for an event is missing, it usually indicates that the guide and playlist are not updated simultaneously. To resolve this, configure your app to sync updates for both the EPG and M3U. If you still see "No information" in the guide, try manually refreshing the EPG. This issue often occurs when the M3U has been updated but the guide information has not.

**Comment by PD-TheKrazy0ne** [comment]
thanks, i just set it to lower interval and updated... seems ok now.  appreciate all you work!
