### ISSUE TITLE
It stopped working 

### ISSUE THREAD

**Issue by disableddabel** [dtankdempse/thetvapp-m3u#7]
Please fix this issue and thank you for making this possible

**Comment by disableddabel** [comment]
I tried again and still doesn’t work

**Comment by dtankdempse** [comment]
It seems TinyURL’s Cloudflare protection has been triggered, likely due to heightened security measures, putting them in protective mode. You can either wait for this to resolve or use the new Bit.ly links I've provided in the main Read Me section.
