### ISSUE TITLE
Fx

### ISSUE THREAD

**Issue by Jantooon** [dtankdempse/thetvapp-m3u#8]
Fx has messed up audio

**Comment by dtankdempse** [comment]
I have no control over the streams.

**Comment by E3RTT** [comment]
how do you scrape the m3u? I'm wanting to learn how and can't find a good guide

**Comment by dtankdempse** [comment]
There's no simple answer, as each site comes with its own unique challenges. Feel free to add me on Discord, and I'd be happy to guide you on how to get started. It might take me a bit to respond, but I will get back to you.

dtanks_86578
