### ISSUE TITLE
Can you please sync the tv channel schedule 

### ISSUE THREAD

**Issue by disableddabel** [dtankdempse/thetvapp-m3u#9]
Can you please sync the tv channel schedule

**Comment by dtankdempse** [comment]
I need more information on what you are talking about here. I don't understand what you mean? Try and describe what you mean in as much detail as possible.

**Comment by disableddabel** [comment]
On the channels it shows what is on but not what’s coming up next

**Comment by disableddabel** [comment]
You should be able to sync it up from the website

**Comment by dtankdempse** [comment]
I'm not sure which app you're using, but the guide provides up to two days of information in the EPG.

**Comment by disableddabel** [comment]
IPTV. SMARTERS PRO

**Comment by dtankdempse** [comment]
![Capture](https://github.com/user-attachments/assets/4bbecd39-c631-42f4-821d-73f4d6986db2)

Check your settings then, because the guide is updating regularly.
